## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [83]:
import numpy as np
import pandas as pd
X1 = np.arange(800).reshape(160, 5)
X2 = np.arange(200).reshape(40, 5)
y = np.zeros(200)
y[:40] = 1
print("Shape of X1: ", X1.shape)
print("Shape of X2: ", X2.shape)
print("Shape of y: ", y.shape)

Shape of X1:  (160, 5)
Shape of X2:  (40, 5)
Shape of y:  (200,)


In [84]:
y.sort()
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
a=y[:160]
b=y[161:200]

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [86]:
from sklearn.model_selection import train_test_split, KFold
import numpy as np

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X1, a, test_size=10, random_state=42)

In [88]:
X_train

array([[ 95,  96,  97,  98,  99],
       [420, 421, 422, 423, 424],
       [ 75,  76,  77,  78,  79],
       [330, 331, 332, 333, 334],
       [120, 121, 122, 123, 124],
       [150, 151, 152, 153, 154],
       [640, 641, 642, 643, 644],
       [735, 736, 737, 738, 739],
       [490, 491, 492, 493, 494],
       [ 80,  81,  82,  83,  84],
       [375, 376, 377, 378, 379],
       [ 90,  91,  92,  93,  94],
       [ 60,  61,  62,  63,  64],
       [ 45,  46,  47,  48,  49],
       [155, 156, 157, 158, 159],
       [755, 756, 757, 758, 759],
       [485, 486, 487, 488, 489],
       [280, 281, 282, 283, 284],
       [655, 656, 657, 658, 659],
       [520, 521, 522, 523, 524],
       [680, 681, 682, 683, 684],
       [390, 391, 392, 393, 394],
       [300, 301, 302, 303, 304],
       [575, 576, 577, 578, 579],
       [ 10,  11,  12,  13,  14],
       [615, 616, 617, 618, 619],
       [225, 226, 227, 228, 229],
       [210, 211, 212, 213, 214],
       [345, 346, 347, 348, 349],
       [450, 4

In [89]:
y_test 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
from sklearn.model_selection import train_test_split, KFold
import numpy as np

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X2, b, test_size=4, random_state=42)

In [93]:
X_train

array([[ 95,  96,  97,  98,  99],
       [420, 421, 422, 423, 424],
       [ 75,  76,  77,  78,  79],
       [330, 331, 332, 333, 334],
       [120, 121, 122, 123, 124],
       [150, 151, 152, 153, 154],
       [640, 641, 642, 643, 644],
       [735, 736, 737, 738, 739],
       [490, 491, 492, 493, 494],
       [ 80,  81,  82,  83,  84],
       [375, 376, 377, 378, 379],
       [ 90,  91,  92,  93,  94],
       [ 60,  61,  62,  63,  64],
       [ 45,  46,  47,  48,  49],
       [155, 156, 157, 158, 159],
       [755, 756, 757, 758, 759],
       [485, 486, 487, 488, 489],
       [280, 281, 282, 283, 284],
       [655, 656, 657, 658, 659],
       [520, 521, 522, 523, 524],
       [680, 681, 682, 683, 684],
       [390, 391, 392, 393, 394],
       [300, 301, 302, 303, 304],
       [575, 576, 577, 578, 579],
       [ 10,  11,  12,  13,  14],
       [615, 616, 617, 618, 619],
       [225, 226, 227, 228, 229],
       [210, 211, 212, 213, 214],
       [345, 346, 347, 348, 349],
       [450, 4

In [94]:
y_test 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])